spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:h2:mem:db_dev;MODE=MySQL
  mvc:
    problemdetails:
      enabled: false

logging:
  level:
    org.hibernate.sql: debug
    org.hibernate.orm.jdbc.bind: trace
    org.hibernate.orm.jdbc.extract: trace
    org.springframework.transaction.interceptor: trace

custom:
  jwt:
    secretKey: RjnNJn0bpT1nvG1AgH2vbTOvkB1iMzlX3+Evusj2n/U=
    accessTokenExpiration: 3600000  # 1 시간 (밀리초)
    refreshTokenExpiration: 604800000  # 7 일 (밀리초)
    expireTime: 1
  toss:
    payment:
      secret-key: test_gsk_docs_OaPz8L5KdmQXkzRz3y47BMw6
